name: generate-pdf-artifacts

on:
  pull_request: []
  push:

jobs:
  GeneratePdfArtifacts:
    name: Generate PDFs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

        # See https://github.com/rseng/pdf-generator for release
      - name: Generate Full PDF Template      
        uses: rseng/pdf-generator@master
        with:        

          # The latex template to use (defaults to one here)
          #latex_template: templates/latex.template.joss

          # The markdown file to render,path is relative to repository
          # make sure that images are also relative to the root in the file
          paper_markdown: README.md

          # The paper pdf to save
          paper_outfile: README.pdf

          # Bibliography file, if existing
          #bibtex: paper/paper.bib

          # A path to a png logo file
          #png_logo: paper/sorse.png

          # One of "minimal" or "pdf" for the template with image, etc.
          pdf_type: pdf

          # A variables file to use
          #variables_file: templates/joss-variables.txt
 
          # A mapping file to u0se
          #mapping_file: templates/joss-mapping.txt

      - name: Upload full templated pdf as artifact
        uses: actions/upload-artifact@v2-preview
        with:
          name: full-pdf
          path: README.pdf

